package codegen

import (
	"testing"

	"github.com/aallbrig/beetree-cli/internal/model"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func sampleSpec() *model.TreeSpec {
	return &model.TreeSpec{
		Version: "1.0",
		Metadata: model.Metadata{
			Name:        "enemy-ai",
			Description: "Enemy patrol and combat AI",
			Author:      "test",
		},
		Blackboard: []model.BlackboardVar{
			{Name: "target", Type: "object", Description: "Current target entity"},
			{Name: "health", Type: "float", Default: 100.0},
			{Name: "is_alerted", Type: "bool", Default: false},
		},
		CustomNodes: []model.CustomNodeDef{
			{
				Name:        "DetectNearbyEnemy",
				Type:        "condition",
				Description: "Checks for enemies within radius",
				Parameters: []model.ParameterDef{
					{Name: "detection_radius", Type: "float", Default: 15.0},
				},
				BlackboardReads:  []string{"target"},
				BlackboardWrites: []string{"target", "is_alerted"},
			},
		},
		Tree: model.NodeSpec{
			Type: "selector",
			Name: "root",
			Children: []model.NodeSpec{
				{
					Type: "sequence",
					Name: "engage",
					Children: []model.NodeSpec{
						{Type: "condition", Name: "has_target", Node: "HasTarget"},
						{Type: "action", Name: "attack", Node: "Attack"},
					},
				},
				{
					Type: "sequence",
					Name: "detect",
					Children: []model.NodeSpec{
						{Type: "condition", Name: "detect_enemy", Node: "DetectNearbyEnemy"},
						{Type: "action", Name: "alert", Node: "Alert"},
					},
				},
				{Type: "action", Name: "patrol", Node: "Patrol"},
			},
		},
	}
}

func TestCollectLeafNodes(t *testing.T) {
	spec := sampleSpec()
	leaves := CollectLeafNodes(&spec.Tree)

	assert.Len(t, leaves, 5)

	names := make([]string, len(leaves))
	for i, l := range leaves {
		names[i] = l.Name
	}
	assert.Contains(t, names, "has_target")
	assert.Contains(t, names, "attack")
	assert.Contains(t, names, "patrol")
}

func TestCollectLeafNodes_UniqueByNode(t *testing.T) {
	spec := &model.TreeSpec{
		Tree: model.NodeSpec{
			Type: "sequence",
			Name: "root",
			Children: []model.NodeSpec{
				{Type: "action", Name: "attack1", Node: "Attack"},
				{Type: "action", Name: "attack2", Node: "Attack"},
			},
		},
	}

	leaves := CollectLeafNodes(&spec.Tree)
	assert.Len(t, leaves, 2, "should return all leaves even with same Node class")
}

func TestCollectActions(t *testing.T) {
	spec := sampleSpec()
	actions := CollectActions(&spec.Tree)

	assert.Len(t, actions, 3)
	for _, a := range actions {
		assert.Equal(t, "action", a.Type)
	}
}

func TestCollectConditions(t *testing.T) {
	spec := sampleSpec()
	conditions := CollectConditions(&spec.Tree)

	assert.Len(t, conditions, 2)
	for _, c := range conditions {
		assert.Equal(t, "condition", c.Type)
	}
}

func TestCollectUniqueNodeClasses(t *testing.T) {
	spec := &model.TreeSpec{
		Tree: model.NodeSpec{
			Type: "sequence",
			Name: "root",
			Children: []model.NodeSpec{
				{Type: "action", Name: "attack1", Node: "Attack"},
				{Type: "action", Name: "attack2", Node: "Attack"},
				{Type: "condition", Name: "check", Node: "HasTarget"},
			},
		},
	}

	classes := CollectUniqueNodeClasses(&spec.Tree)
	assert.Len(t, classes, 2)
	assert.Contains(t, classes, "Attack")
	assert.Contains(t, classes, "HasTarget")
}

func TestBuildTemplateData(t *testing.T) {
	spec := sampleSpec()
	data := BuildTemplateData(spec)

	assert.Equal(t, "enemy-ai", data.TreeName)
	assert.Equal(t, "EnemyAi", data.TreeClassName)
	assert.Equal(t, "Enemy patrol and combat AI", data.Description)
	assert.Len(t, data.Blackboard, 3)
	assert.Len(t, data.Actions, 3)
	assert.Len(t, data.Conditions, 2)
	require.NotNil(t, data.RootNode)
}

func TestToPascalCase(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"enemy-ai", "EnemyAi"},
		{"patrol_and_engage", "PatrolAndEngage"},
		{"simple", "Simple"},
		{"already-PascalCase", "AlreadyPascalcase"},
		{"my_tree-name", "MyTreeName"},
	}

	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			assert.Equal(t, tt.expected, ToPascalCase(tt.input))
		})
	}
}

func TestToSnakeCase(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"EnemyAi", "enemy_ai"},
		{"HasTarget", "has_target"},
		{"BTNode", "bt_node"},
		{"simple", "simple"},
	}

	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			assert.Equal(t, tt.expected, ToSnakeCase(tt.input))
		})
	}
}

func TestGeneratedFileHeader(t *testing.T) {
	header := GeneratedFileHeader("enemy-ai.beetree.yaml", "//")
	assert.Contains(t, header, "AUTO-GENERATED by BeeTree CLI")
	assert.Contains(t, header, "enemy-ai.beetree.yaml")
	assert.Contains(t, header, "DO NOT EDIT")
}

func TestStubFileHeader(t *testing.T) {
	header := StubFileHeader("enemy-ai.beetree.yaml", "//")
	assert.Contains(t, header, "Generated by BeeTree CLI")
	assert.Contains(t, header, "EDIT THIS FILE")
	assert.Contains(t, header, "enemy-ai.beetree.yaml")
}

func TestGenerateOutput(t *testing.T) {
	spec := sampleSpec()
	data := BuildTemplateData(spec)

	files, err := GenerateFromTemplate("test", "Hello {{.TreeClassName}}", data)
	require.NoError(t, err)
	assert.Equal(t, "Hello EnemyAi", files)
}

func TestBlackboardVarData(t *testing.T) {
	spec := sampleSpec()
	data := BuildTemplateData(spec)

	found := false
	for _, bv := range data.Blackboard {
		if bv.Name == "health" {
			found = true
			assert.Equal(t, "float", bv.Type)
		}
	}
	assert.True(t, found, "should include health blackboard var")
}
